services:
  - type: web
    name: agriculture-disease-api
    runtime: python
    plan: starter
    region: singapore
    branch: main
    
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python scripts/download_models_render.py
    
    startCommand: gunicorn app.main:app \
      --workers 2 \
      --worker-class uvicorn.workers.UvicornWorker \
      --bind 0.0.0.0:$PORT

    healthCheckPath: /health
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      
      - key: APP_NAME
        value: Agriculture Disease Detection API
      
      - key: DEBUG
        value: false
      
      - key: HOST
        value: 0.0.0.0
      
      - key: PORT
        value: 10000
      
      - key: LOG_LEVEL
        value: INFO
      
      - key: CROP_CONFIDENCE_THRESHOLD
        value: 0.60
      
      - key: DISEASE_CONFIDENCE_THRESHOLD
        value: 0.50
      
      - key: MAX_IMAGE_SIZE
        value: 10485760
      
      - key: PLANTIX_API_KEY
        sync: false

      - key: HF_REPO_ID
        value: somveersingh-23/agriculture-disease-detection
      
      - key: HF_TOKEN
        sync: false

    autoDeploy: true

    disk:
      name: model-storage
      mountPath: /app/app/models
      sizeGB: 2
